version: '3.4'
services:
  teku.avado.dnp.dappnode.eth:
    image: 'teku.avado.dnp.dappnode.eth:0.0.17'
    build:
      context: ./build
      args:
        TEKU_VERSION: 22.8.1
    volumes:
      - 'data:/data'
    environment:
      - JAVA_OPTS=-Xmx3g
      - EXTRA_OPTS=
volumes:
  data: {}
